Feature/gan UI
RichardObi/medigan pull request #12
Opened 2022-06-09 09:41 UTC by faildeny

### User interface to manually generate image sample by manipulating the random latent vector

This is still WIP

The z vector size is being loaded from the global.json file. If such an attribute does not exist, it is None by default. 
The model packages need to have an z  keyword argument input in the `generate()` method.

<img width="752" alt="Screenshot 2022-06-09 at 11 38 43" src="https://user-images.githubusercontent.com/29950558/172817018-6e725bb0-91d8-4013-b0dd-fda086091ec1.png">

#### Update 

- Fixed sliders update when offset is changed
- Added conditional GAN support

<img width="752" alt="Screenshot 2022-06-15 at 15 19 54" src="https://user-images.githubusercontent.com/29950558/173837113-14d8f5ef-546d-41f7-b41d-37876402bdda.png">

2022-06-11 17:53 UTC, RichardObi requested changes
Hi Greg,
great work on the GAN UI! Thank you! I have tried the UI and I really like it. It is a useful tool for model exploration. I have left a few comments especially regarding the integration in a dedicated visualization module of medigan. I would add that it would be nice in the visualization to have a concise legend at the bottom of the visualization where the different parts are explained, such as i) "Input vector", ii) "offset", iii) "z1-z20", iv) "seed", and  v) "reset".

2022-06-13 08:26 UTC, faildeny commented on src/medigan/preview_ui.py
> +z = torch.randn(num_samples, nz, 1, 1, device=device)
Good point, changed.

2022-06-13 08:27 UTC, faildeny commented on config/global.json
> +        "z_size": 200
Added

2022-06-13 08:27 UTC, faildeny commented on config/global.json
> +        "z_size": 200
Added

2022-06-13 09:44 UTC, faildeny commented on src/medigan/preview_ui.py
> +
Script has been moved to a class

2022-06-14 11:23 UTC, faildeny commented on config/global.json
> +        "z_size": 100
Renamed to `input_latent_vector_size`

2022-06-23 10:44 UTC, faildeny commented on src/medigan/model_visualizer.py
> +class ModelVisualizer:
I expanded the docstring with attributes and description.

2022-06-23 14:22 UTC, faildeny commented on src/medigan/model_visualizer.py
> +ModelVisualizer("00002_DCGAN_MMG_MASS_ROI")
done

2022-06-23 14:26 UTC, faildeny commented on src/medigan/model_visualizer.py
> +        generators = Generators()
I've moved this to the Generators class. However, it's not 100% similar to model_executor scheme. For now, I don't see it necessary to check if the visualizer has been initialized or not. It is being created on the go.

2022-06-24 11:17 UTC, faildeny commented on src/medigan/model_visualizer.py
> +        if self.conditional:
Added

2022-06-24 11:59 UTC, faildeny commented on src/medigan/model_visualizer.py
> +        fig.suptitle(
I added the legend, but for model description I have some doubts. The comment section is quite long. I don't think it's that relevant and also it's really hard to format such a big text in matplotlib. That's an example:
`A Fast generative adversarial network (FastGAN) that generates a 4 dimensional output containing an RGB image (channels 1-3) and a segmentation mask (channel 4). FASTGAN is from the paper 'Towards Faster and Stabilized GAN Training for High-fidelity Few-shot Image Synthesis' in ICLR 2021. The RGB images are images of polyps and the segmentation mask indicates the location and shape of the polyp on the image. Pixel dimensions are 256x256. The model was trained on gastrointestinal endoscopy imaging data from the HyperKvasir dataset by Borgli et al (2020, 'https://doi.org/10.1038/s41597-020-00622-y'). The uploaded ZIP file contains the files FastGAN_all_50000.pth (model weight), __init__.py (image generation method and utils), a requirements.txt, a LICENSE file, the MEDIGAN metadata, the source code from the repository ('https://github.com/vlbthambawita/singan-seg-polyp'), and a test.sh file to run the model, and a folder 'examples/' with a few generated images.`
I think the title section may be a better idea (or just model_id, as it is now)

2022-06-24 12:03 UTC, faildeny commented
Updated UI:
<img width="752" alt="Screenshot 2022-06-24 at 14 03 34" src="https://user-images.githubusercontent.com/29950558/175530462-4a347825-bb8b-4919-b774-9e7fb56ae885.png">

2022-06-24 12:28 UTC, RichardObi commented on src/medigan/model_visualizer.py
> +        fig.suptitle(
Yes, it is true that the model description can be quite long - and probably too long for the interface. As you suggested, let's use the title instead, which for fastGAN would be for instance: 
`FastGAN Model for Patch Generation of Polyps with Corresponding Segmentation Masks (Trained on HyperKvasir)`

2022-06-24 12:49 UTC, RichardObi commented on src/medigan/model_visualizer.py
> +            raise ValueError("Visualization of this model is not supported")
```suggestion
            raise ValueError(f"{self.model_id}: Visualization of this model is not supported. Reason: This model does not use a random vector 'z' as input, which is needed for visualization. This is determined via the absence of the 'input_latent_vector_size' variable in this model's metadata in config/global.json.")
```

2022-06-24 12:49 UTC, RichardObi commented on src/medigan/model_visualizer.py
> +class ModelVisualizer:
Looks great! 
Could you also add docstring to the functions, i.e. `visualize()` `_unpack_output()`, and to `update()` `reset()` `new_seed()` ?

2022-06-24 12:49 UTC, RichardObi commented on src/medigan/generators.py
> +    def visualize(self, model_id: str):
Also here, it would be good to have the docstring analogous to the other functions of the Generators() class.

2022-06-24 12:49 UTC, RichardObi commented on src/medigan/model_visualizer.py
> +        generators = Generators()
Yes, I think it is fine for now this way i.e. to **not** search for already initialized visualizers, as (a) there is no state stored in a visualizer instance and (b) there are no elements in the visualizer instance that have long loading times during initialization.

2022-06-29 08:59 UTC, faildeny commented on src/medigan/model_visualizer.py
> +        fig.suptitle(
I've added the model title under the model name.

2022-06-29 09:01 UTC, faildeny commented
I know the UI is quite chaotic, but it's kind of unavoidable in matplotlib.
<img width="778" alt="Screenshot 2022-06-29 at 11 00 20" src="https://user-images.githubusercontent.com/29950558/176396967-cbf0ac2c-a7d3-44cc-8277-7d793955ca16.png">

2022-06-29 10:29 UTC, RichardObi commented
Hi!! 
I tested the feature/gan_ui with the latest changes for models 00012, 0009, and 0002, and found the following:

**For model 00012** (class conditional GAN with tuple return value), I got the following error
```
>>> generators.visualize(model_id="00012_C-DCGAN_MMG_MASSES")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../medigan/src/medigan/generators.py", line 1368, in visualize
    ModelVisualizer(model_executor, config).visualize()
  File "..../medigan/src/medigan/model_visualizer.py", line 78, in visualize
    image, mask = self._unpack_output(output)
  File ".../medigan/src/medigan/model_visualizer.py", line 269, in _unpack_output
    if len(output[0][1].size()) > 1:
AttributeError: 'str' object has no attribute 'size'
```

**For model 00009** (Mask + image generating GAN with tuple return value), I got the following error:
```
>>> generators.visualize(model_id="00009_PGGAN_POLYP_PATCHES_W_MASKS")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../medigan/src/medigan/generators.py", line 1368, in visualize
    ModelVisualizer(model_executor, config).visualize()
  File ".../medigan/src/medigan/model_visualizer.py", line 78, in visualize
    image, mask = self._unpack_output(output)
  File ".../medigan/src/medigan/model_visualizer.py", line 269, in _unpack_output
    if len(output[0][1].size()) > 1:
TypeError: 'int' object is not callable
```

**For model 00002** (Noise-Vector to image GAN with list return value), it worked and looked like this:
<img width="961" alt="image" src="https://user-images.githubusercontent.com/47958412/176412256-bcee62e7-020e-4cbb-b25d-6c55c2c09a27.png">

1. The title text overlaps the generated image and the "generated image" caption. This would need a change. I know such alignment is difficult in matplotlib. If we stick to matplotlib for now, maybe a solution would be to display this "title" text of the model on top of the caption.
2. The image is higher up than the sliders. Maybe it would help to move the entire caption below slider and image, so that image and slider are more r less on the same level.

**Merging this PR:**
- For merging I suggest to advertise the visualization feature with a code snippet in the Readme.
- The docstrings (descr, params, returns) for the functions in model_visualizer is still missing and would be needed, as it auto-generates part of the read-the-docs documentation.
- Optionally, a test for visualization could be added to the ci tests in tests/test_generator.py

_With the above issues fixed, there will be nothing else needed to merge this PR into main._

2022-07-04 10:34 UTC, RichardObi approved these changes
Hi @faildeny, fantastic changes - you have addressed all of the issues I mentioned in my previous reviews. Well done!! 

I tested several models and all worked fine. Only thing I noticed was that model `00009_PGGAN_POLYP_PATCHES_W_MASKS` was not producing the expected masks. However, I think that problem is within the model and not related to the visualization. Also  `00010_FASTGAN_POLYP_PATCHES_W_MASKS` produced the masks only for some latent codes, so I guess it is the same for 00009.

Another thing I noticed is that the latent code vectors are now divided by 25 instead of 10. When you merge this branch, maybe could you make this divider a parameter of the `visualize()` function. It would be cool to try out different slider divisions when exploring a model' latent space. For example:

`    def visualize(self, auto_close=False, slider_divider:int=10):
        """
        Visualize the models output. This method is called by the user.
        It opens up a user interface with available controls.

        Parameters
        ----------
        auto_close: bool
            Flag for closing the user interface automatically after time. Used while testing.
        slider_divider: int
            The model's latent input vector z will be divided by this number.
            The result of this division determines the number of sliders that are show in the UI

        Returns
        -------
        None
        """
`

Great work! Let's merge 👍

2022-07-04 11:28 UTC, faildeny commented
I've added a slider parameter. If tests pass, I will merge.

2022-07-04 12:42 UTC, merged